apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:    
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

